### ISSUE TITLE
能否增加一个类似功能？直接复制Markdown代码。

### ISSUE THREAD

**Issue by Mingyi** [liyaodong/image-uploader#1]
![](http://ww2.sinaimg.cn/large/62ad0e9agw1f6c5yyyjd9j20m80fc3zz.jpg)

**Comment by nothingrealhappen** [comment]
哈哈哈，我最初也是想做 Markdown 的，后来感觉还是 图片地址方便。既然有人提了那就在选项里加一个吧。
