### ISSUE TITLE
上传图片报错，区域问题

### ISSUE THREAD

**Issue by lwabish** [liyaodong/image-uploader#3]
配置好后上传图片会提示：
{"error":"incorrect region, please use up-z1.qiniu.com"}
我的 bucket 是华北的。

**Comment by nothingrealhappen** [comment]
似乎是因为七牛云更改了上传地址导致的，现在会针对不同的 region 指定不同的图片上传地址。稍后会更新一下，自动获取 upload url，修复这个问题 :p

**Comment by nothingrealhappen** [comment]
在 `0.0.6` 版本里修复了这个问题，1个小时内 Chorme 浏览器应该会自动同步到最新版

**Comment by lwabish** [comment]
好迅速！多谢。
